#!/usr/bin/env python3
"""Generate the Objective-C version header from the repository VERSION file."""
import argparse
from pathlib import Path
from versioning import VERSION

HEADER = f'''// Generated by Integration/generate_version_header.py. Do not hand-edit.\n#pragma once\n#define RC_ANALYSIS_VERSION @"{VERSION}"\n'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("output", nargs="?", default=str(Path(__file__).resolve().parent.parent / "Sources/RCVersion.generated.h"))
    a = ap.parse_args()
    out = Path(a.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    old = out.read_text(encoding="utf-8") if out.exists() else None
    if old != HEADER:
        out.write_text(HEADER, encoding="utf-8")
        print(f"generated: {out} ({VERSION})")
    else:
        print(f"version header current: {out} ({VERSION})")


if __name__ == "__main__":
    main()
